apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flow-pilot-secrets
  namespace: flow-pilot
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: flow-pilot-store
    kind: SecretStore
  target:
    name: flow-pilot-backend-secrets
    creationPolicy: Owner
  data:
    # Backend Specific Secrets
    - secretKey: INTERSWITCH_CLIENT_ID
      remoteRef:
        key: INTERSWITCH_CLIENT_ID
    - secretKey: INTERSWITCH_CLIENT_SECRET
      remoteRef:
        key: INTERSWITCH_CLIENT_SECRET
    - secretKey: INTERSWITCH_WALLET_PIN
      remoteRef:
        key: INTERSWITCH_WALLET_PIN
    - secretKey: GROQ_API_KEY
      remoteRef:
        key: GROQ_API_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DB_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: GOOGLE_CLIENT_SECRET
