apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: flow-pilot-store
  namespace: flow-pilot
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: flow-pilot-infisical-token
            key: clientId
          clientSecret:
            name: flow-pilot-infisical-token
            key: clientSecret
      hostAPI: "http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api"
      secretsScope:
        projectSlug: "flowpilot-lifh"  
        environmentSlug: "prod"
        secretsPath: "/"
