apiVersion: v1
kind: Service
metadata:
  name: flow-pilot-frontend
  namespace: flow-pilot
spec:
  selector:
    app: flow-pilot-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30095
  type: NodePort
