apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: flow-pilot
data:
  NEXT_PUBLIC_API_URL: "https://api.flowpilot.club/api/v1"
  BACKEND_URL: "http://flow-pilot-backend.flow-pilot.svc.cluster.local:8000"
